### ISSUE TITLE
Which version of underscore.js they using ?

### ISSUE THREAD

**Issue by gsivaprabu** [victorleungtw/lynda-underscore#1]
Hi @victorleungtw ,

Which version of underscore.js they using ?

regards,
@gsivaprabu

**Comment by victorleungtw** [comment]
@gsivaprabu Sorry, I don't remember, it was a year ago.

**Comment by gsivaprabu** [comment]
Thanks lot





regards,

[image: --]
Sivaprabu Ganesan
[image: http://]about.me/gsivaprabu
<http://about.me/gsivaprabu?promo=email_sig>


<http://about.me/gsivaprabu>

**Comment by gsivaprabu** [comment]
I have using this example with latest  Underscore.js 1.8.3 maximum of functionalities working @victorleungtw ..
